<?xml version="1.0" encoding="utf-8"?>
<test>
    <description>
    3D explicit interior-penalty diffusion on a mixed prism/hexahedron mesh.

    Added for coverage rather than to reproduce a particular answer. Every
    other diffusion case in this solver is two dimensional, and every three
    dimensional case is advection only, so nothing here exercised the
    interior-penalty trace path on a mesh carrying more than one element type.
    That gap is why a library bug in the per-block trace data indexing - see
    the commit that adds this test - went unseen on the ADR side and surfaced
    only in the compressible solver.

    The mesh matters more than the physics. Prisms carry both quadrilateral and
    triangular faces while hexahedra carry only quadrilaterals, so the global
    trace splits into more than one block. Code that fetches per-block trace
    data for block 0 alone and indexes it with a whole-trace offset is correct
    for the first block and wrong for the rest; a single element type gives one
    block and cannot show it. The mesh is generated by
    solvers/CompressibleFlowSolverRedesign/Tests/MakeChanFlow3DMesh.py, which
    is also where the geometry and the element mix are documented.

    Be aware of what this test does *not* do. It does not discriminate on the
    bug that motivated it: with the fix reverted it returns the same values to
    every printed digit, because the out-of-range read lands on adjacent valid
    trace data on this mesh. The guard against that failure is the ASSERTL1 in
    DiffusionScalarIPTraceFluxOpImpl, which is deterministic and fires in a
    debug build. This case is here so that the *path* is walked at all.

    The initial condition is separable and constant along z, and vanishes on
    all four Dirichlet walls at every time, so it decays as
    exp(-((pi/2)^2 + (pi/2)^2) t) and the exact solution is known. The
    remaining error is dominated by the first-order time integration; the
    spatial error alone is about 1.25e-3. The timestep is set by the explicit
    diffusion stability limit on the wall-clustered spacing - 2e-4 diverges.
    </description>
    <executable>ADRSolverRedesign</executable>
    <parameters>ExDiffusion_3D_IP_prism_hex.xml</parameters>
    <files>
        <file description="Session File">ExDiffusion_3D_IP_prism_hex.xml</file>
    </files>
    <metrics>
        <metric type="L2" id="1">
            <value variable="u" tolerance="1e-8">0.00127548</value>
        </metric>
        <metric type="Linf" id="2">
            <value variable="u" tolerance="1e-8">0.00806843</value>
        </metric>
    </metrics>
</test>
