#
# NektarCUDA.cmake
#
# Sets up cmake variables needed for using CUDA in Nektar++
#

IF(CMAKE_VERSION VERSION_LESS "3.18.0")
    MESSAGE(FATAL_ERROR "CUDA compilation requires CMake version >= 3.18")
ENDIF()

IF (NOT ${CMAKE_CUDA_COMPILER_ID} STREQUAL "NVIDIA")
    MESSAGE(FATAL_ERROR "CUDA compilation requires nvcc compiler")
ENDIF()

SET(BOOST_MIN_VERSION "1.76.0")

IF(NOT CUDA_MIN_VERSION)
    SET(CUDA_MIN_VERSION "11.1")
ENDIF()

IF (NOT DEFINED CMAKE_CUDA_STANDARD)
    SET(CMAKE_CUDA_STANDARD 17)
    SET(CMAKE_CUDA_STANDARD_REQUIRED ON)
ENDIF()

ADD_COMPILE_OPTIONS($<$<COMPILE_LANGUAGE:CUDA>:$<$<CXX_COMPILER_ID:MSVC>:-Xcompiler="/permissive-">>)
ADD_COMPILE_OPTIONS($<$<COMPILE_LANGUAGE:CUDA>:-Xcudafe>)
ADD_COMPILE_OPTIONS($<$<COMPILE_LANGUAGE:CUDA>:--diag_suppress=550>)

SET(CUDA_SEPARABLE_COMPILATION ON)

IF (NEKTAR_DEVICE_ARCH)
    IF(NOT NEKTAR_DEVICE_ARCH MATCHES "^sm_[0-9]+$")
        MESSAGE(FATAL_ERROR "For Nvidia GPU, NEKTAR_DEVICE_ARCH must be specified as sm_XX, got '${NEKTAR_DEVICE_ARCH}'")
    ENDIF()
    STRING(REPLACE "_" ";" ARCH ${NEKTAR_DEVICE_ARCH})
    LIST(GET ARCH 1 ARCH)
    ADD_COMPILE_DEFINITIONS(__NEKTAR_DEVICE_ARCH__="compute_${ARCH}")
    SET(CMAKE_CUDA_ARCHITECTURES ${ARCH})
ELSE()
    IF(CMAKE_VERSION VERSION_LESS "3.24.0")
        MESSAGE("Please consider to switch to CMake 3.24.0")
        SET(CMAKE_CUDA_ARCHITECTURES 70 72 75 80 86 90)
    ELSE()
        SET(CMAKE_CUDA_ARCHITECTURES native)
    ENDIF()
ENDIF()

ENABLE_LANGUAGE(CUDA)
SET(CMAKE_CUDA_FLAGS "--extended-lambda --expt-relaxed-constexpr")
FIND_PACKAGE(CUDAToolkit ${CUDA_MIN_VERSION} REQUIRED)
INCLUDE_DIRECTORIES(${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES})

OPTION(NEKTAR_USE_CUFFT_STATIC
    "Link cuFFT statically to enable store-callback support in NekDeviceFFT"
    OFF)
MARK_AS_ADVANCED(NEKTAR_USE_CUFFT_STATIC)
IF(NEKTAR_USE_CUFFT_STATIC)
    SET(CMAKE_CUDA_RUNTIME_LIBRARY Static)
    SET(CUFFT_LIBRARY CUDA::cufft_static CUDA::culibos)
    MESSAGE(STATUS "NekDeviceFFT: static cuFFT linkage enabled (callbacks supported)")

    IF(CMAKE_CUDA_ARCHITECTURES STREQUAL "native")
        SET(CUFFT_ARCH_FLAGS "-arch=native")
    ELSE()
        SET(CUFFT_ARCH_FLAGS "")
        FOREACH(_a ${CMAKE_CUDA_ARCHITECTURES})
            LIST(APPEND CUFFT_ARCH_FLAGS
                "-gencode" "arch=compute_${_a},code=sm_${_a}")
        ENDFOREACH()
    ENDIF()
ELSE()
    SET(CMAKE_CUDA_RUNTIME_LIBRARY SHARED)
    SET(CUFFT_LIBRARY CUDA::cufft)
ENDIF()

SET(NEKTAR_CUDA_DEPENDS
    CUDA::cudart
    CUDA::cuda_driver
    CUDA::nvrtc
)
SET(CUBLAS_LIBRARY CUDA::cublas)
SET(CUSPARSE_LIBRARY CUDA::cusparse)
SET(CUSOLVER_LIBRARY CUDA::cusolver)
SET(CURAND_LIBRARY CUDA::curand)
