#
# NektarSimSYCL.cmake
#
# Sets up cmake variables needed for using SYCL in Nektar++
#

SET(CMAKE_CXX_STANDARD 20)

SET(NEKTAR_USE_SIMSYCL ON)

ADD_DEFINITIONS(-DSYCL_ENABLE_CPU)
ADD_DEFINITIONS(-DNEKTAR_USE_SIMSYCL)

SET(BOOST_MIN_VERSION "1.76.0")
IF (_SYSTEM_PROCESSOR STREQUAL "aarch64")
    INCLUDE(CheckCXXCompilerFlag)
    CHECK_CXX_COMPILER_FLAG(-mno-outline-atomics NEKTAR_NO_OUTLINE_ATOMICS)
    IF (NEKTAR_NO_OUTLINE_ATOMICS)
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mno-outline-atomics")
    ENDIF()
ENDIF()
