#
# NektarHIP.cmake
#
# Sets up cmake variables needed for using HIP in Nektar++
#

IF(CMAKE_VERSION VERSION_LESS "3.21.0")
    MESSAGE(FATAL_ERROR "CUDA compilation requires CMake version >= 3.21")
ENDIF()

IF(NOT HIP_MIN_VERSION)
    SET(HIP_MIN_VERSION "5.7")
ENDIF()

ADD_DEFINITIONS(-DNEKTAR_ENABLE_HIP)

IF (NOT DEFINED CMAKE_HIP_STANDARD)
    SET(CMAKE_HIP_STANDARD 17)
    SET(CMAKE_HIP_STANDARD_REQUIRED ON)
ENDIF()

ADD_COMPILE_OPTIONS($<$<COMPILE_LANGUAGE:HIP>:$<$<CXX_COMPILER_ID:MSVC>:-Xcompiler="/permissive-">>)

#SET(HIP_SEPARABLE_COMPILATION ON)

IF (NEKTAR_DEVICE_ARCH)
    SET(CMAKE_HIP_ARCHITECTURES ${NEKTAR_DEVICE_ARCH})
ELSE()
    SET(CMAKE_HIP_ARCHITECTURES gfx900 gfx902 gfx906 gfx908 gfx909 gfx90a gfx90c)
ENDIF()

ENABLE_LANGUAGE(HIP)

#SET(NEKTAR_HIP_DEPENDS HIP::HIP)
