#
# NektarKokkos.cmake
#
# Sets up cmake variables needed for using Kokkos in Nektar++
#

OPTION(NEKTAR_ENABLE_KOKKOS "Enable KOKKOS execution" OFF)

IF (NEKTAR_ENABLE_KOKKOS)
    IF(NOT KOKKOS_MIN_VERSION)
        SET(KOKKOS_MIN_VERSION "4.3")
    ENDIF()

    ADD_DEFINITIONS(-DNEKTAR_ENABLE_KOKKOS)

    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DUSING_LATEST_KOKKOS")

    FIND_PACKAGE(Kokkos ${KOKKOS_MIN_VERSION} REQUIRED)

    SET(NEKTAR_KOKKOS_DEPENDS Kokkos::kokkos)
ENDIF (NEKTAR_ENABLE_KOKKOS)
