#
# NektarIntelSYCL.cmake
#
# Sets up cmake variables needed for using SYCL in Nektar++
#

IF (USE_SYCL_BUILTIN_REDUCER)
    ADD_DEFINITIONS(-DUSE_SYCL_BUILTIN_REDUCER)
ENDIF()

IF(CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
    SET(EXTRA_FLAGS -Wno-enum-constexpr-conversion)
ENDIF()

IF (NEKTAR_ENABLE_DEVICE STREQUAL "SYCL-CPU")
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsycl -fsycl-targets=x86_64 ${EXTRA_FLAGS} ")
    ADD_DEFINITIONS(-DSYCL_ENABLE_CPU)
    SET(BOOST_MIN_VERSION "1.76.0")
ELSEIF (NEKTAR_ENABLE_DEVICE STREQUAL "SYCL-CUDA")
    ADD_DEFINITIONS(-DSYCL_ENABLE_CUDA)
    IF (NEKTAR_DEVICE_ARCH)
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsycl -fsycl-targets=nvidia_gpu_${NEKTAR_DEVICE_ARCH} ${EXTRA_FLAGS} ")
    ELSE()
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsycl -fsycl-targets=nvptx64-nvidia-cuda ${EXTRA_FLAGS} ")
    ENDIF()
    SET(CUDA_SEPARABLE_COMPILATION ON)
    SET(BOOST_MIN_VERSION "1.82.0")
ELSEIF (NEKTAR_ENABLE_DEVICE STREQUAL "SYCL-HIP")
    ADD_DEFINITIONS(-DSYCL_ENABLE_HIP)
    IF (NEKTAR_DEVICE_ARCH)
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsycl -fsycl-targets=amd_gpu_${NEKTAR_DEVICE_ARCH} ${EXTRA_FLAGS} ")
    ELSE()
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsycl -fsycl-targets=amdgcn-amd-amdhsa ${EXTRA_FLAGS} ")
    ENDIF()
    SET(BOOST_MIN_VERSION "1.82.0")
ELSEIF (NEKTAR_ENABLE_DEVICE STREQUAL "SYCL-Intel")
    ADD_DEFINITIONS(-DSYCL_ENABLE_INTEL)
    IF (NEKTAR_DEVICE_ARCH)
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsycl -fsycl-targets=intel_gpu_${NEKTAR_DEVICE_ARCH} ${EXTRA_FLAGS} ")
    ELSE()
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsycl -fsycl-targets=spir64_gen ${EXTRA_FLAGS} ")
    ENDIF()
ENDIF()

IF(CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
    FIND_PACKAGE(IntelSYCL REQUIRED)
ENDIF()

INCLUDE(NektarOneMath)
