#
# NektarHIP.cmake
#
# Sets up cmake variables needed for using HIP in Nektar++
#

IF(CMAKE_VERSION VERSION_LESS "3.21.0")
    MESSAGE(FATAL_ERROR "HIP compilation requires CMake version >= 3.21")
ENDIF()

SET(BOOST_MIN_VERSION "1.82.0")

IF (NOT DEFINED CMAKE_HIP_STANDARD)
    SET(CMAKE_HIP_STANDARD 17)
    SET(CMAKE_HIP_STANDARD_REQUIRED ON)
ENDIF()

ADD_COMPILE_OPTIONS($<$<COMPILE_LANGUAGE:HIP>:$<$<CXX_COMPILER_ID:MSVC>:-Xcompiler="/permissive-">>)
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-pass-failed ")

IF (NEKTAR_DEVICE_ARCH)
    ADD_COMPILE_DEFINITIONS(__NEKTAR_DEVICE_ARCH__="${NEKTAR_DEVICE_ARCH}")
    SET(CMAKE_HIP_ARCHITECTURES ${NEKTAR_DEVICE_ARCH})
ELSE()
    SET(CMAKE_HIP_ARCHITECTURES gfx900 gfx902 gfx906 gfx908 gfx909 gfx90a gfx90c)
ENDIF()

ENABLE_LANGUAGE(HIP)

IF(WIN32)
    SET(ROCM_ROOT
        "$ENV{HIP_PATH}"
        CACHE PATH
        "Root directory of the ROCm installation"
    )
ELSE()
    SET(ROCM_ROOT
        "/opt/rocm"
        CACHE PATH
        "Root directory of the ROCm installation"
    )
ENDIF()

LIST(APPEND CMAKE_PREFIX_PATH "${ROCM_ROOT}")

FIND_PACKAGE(HIP REQUIRED)
SET(CMAKE_HIP_FLAGS "${CMAKE_CXX_FLAGS} -D__NEK_HIPCC__")
FIND_PACKAGE(HIPBLAS REQUIRED)
FIND_PACKAGE(HIPSPARSE REQUIRED)
FIND_PACKAGE(HIPSOLVER REQUIRED)
FIND_PACKAGE(HIPFFT REQUIRED)
FIND_PACKAGE(HIPRAND REQUIRED)
FIND_LIBRARY(HIPRTC_LIB hiprtc HINTS ${HIP_PATH}/lib /opt/rocm/lib)
SET(NEKTAR_HIP_DEPENDS
  hip::host
  hip::device
  roc::hipblas
  roc::hipsparse
  roc::hipsolver
  hip::hipfft
  hip::hiprand
  ${HIPRTC_LIB}
  )
