#
# NektarCUDA.cmake
#
# Sets up cmake variables needed for using CUDA in Nektar++
#

IF(CMAKE_VERSION VERSION_LESS "3.18.0")
    MESSAGE(FATAL_ERROR "CUDA compilation requires CMake version >= 3.18")
ENDIF()

SET(BOOST_MIN_VERSION "1.76.0")

IF(NOT CUDA_MIN_VERSION)
    SET(CUDA_MIN_VERSION "11.1")
ENDIF()

ADD_DEFINITIONS(-DNEKTAR_ENABLE_CUDA)

IF (NOT DEFINED CMAKE_CUDA_STANDARD)
    SET(CMAKE_CUDA_STANDARD 17)
    SET(CMAKE_CUDA_STANDARD_REQUIRED ON)
ENDIF()

ADD_COMPILE_OPTIONS($<$<COMPILE_LANGUAGE:CUDA>:$<$<CXX_COMPILER_ID:MSVC>:-Xcompiler="/permissive-">>)

SET(CUDA_SEPARABLE_COMPILATION ON)
SET(CMAKE_CUDA_RUNTIME_LIBRARY SHARED)

IF (NEKTAR_DEVICE_ARCH)
    STRING(REPLACE "_" ";" ARCH ${NEKTAR_DEVICE_ARCH})
    LIST(GET ARCH 1 ARCH)
    SET(CMAKE_CUDA_ARCHITECTURES ${ARCH})
ELSE()
    IF(CMAKE_VERSION VERSION_LESS "3.24.0")
        MESSAGE("Please consider to switch to CMake 3.24.0")
        SET(CMAKE_CUDA_ARCHITECTURES 60 61 62 70 72 75 80 86 90)
    ELSE()
        SET(CMAKE_CUDA_ARCHITECTURES native)
    ENDIF()
ENDIF()

ENABLE_LANGUAGE(CUDA)
SET(CMAKE_CUDA_FLAGS "--extended-lambda --expt-relaxed-constexpr")
FIND_PACKAGE(CUDAToolkit ${CUDA_MIN_VERSION} REQUIRED)
INCLUDE_DIRECTORIES(${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES})
SET(NEKTAR_CUDA_DEPENDS
  CUDA::cudart
  CUDA::cuda_driver
  CUDA::cublas
  CUDA::cusparse
  CUDA::cusolver
  CUDA::cufft
  CUDA::curand
  )
