#
# NektarIntelSYCL.cmake
#
# Sets up cmake variables needed for using SYCL in Nektar++
#

IF(CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
    SET(EXTRA_FLAGS -Wno-enum-constexpr-conversion)
ENDIF()

IF (NEKTAR_ENABLE_DEVICE STREQUAL "SYCL-CPU")
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsycl -fsycl-targets=x86_64 ${EXTRA_FLAGS} ")
    ADD_DEFINITIONS(-DSYCL_ENABLE_CPU)
    SET(BOOST_MIN_VERSION "1.76.0")
ELSEIF (NEKTAR_ENABLE_DEVICE STREQUAL "SYCL-CUDA")
    ADD_DEFINITIONS(-DSYCL_ENABLE_CUDA)
    IF (NEKTAR_DEVICE_ARCH)
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsycl -fsycl-targets=nvidia_gpu_${NEKTAR_DEVICE_ARCH} ${EXTRA_FLAGS} ")
    ELSE()
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsycl -fsycl-targets=nvptx64-nvidia-cuda ${EXTRA_FLAGS} ")
    ENDIF()
    SET(CUDA_SEPARABLE_COMPILATION ON)
    SET(BOOST_MIN_VERSION "1.82.0")
ELSEIF (NEKTAR_ENABLE_DEVICE STREQUAL "SYCL-HIP")
    ADD_DEFINITIONS(-DSYCL_ENABLE_HIP)
    IF(NOT HIP_CXX_COMPILER)
        FIND_PATH(HIP_CXX_COMPILER clang++ HINTS ENV HIPROOT ENV ROCM_PATH)
    ENDIF()
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsycl -fsycl-targets=amdgcn-amd-amdhsa -Xsycl-target-backend --offload-arch=${NEKTAR_DEVICE_ARCH} ${EXTRA_FLAGS} ")
    SET(BOOST_MIN_VERSION "1.82.0")
ELSEIF (NEKTAR_ENABLE_DEVICE STREQUAL "SYCL-Intel")
    ADD_DEFINITIONS(-DSYCL_ENABLE_INTEL)
    IF (NEKTAR_DEVICE_ARCH)
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsycl -fsycl-targets=intel_gpu_${NEKTAR_DEVICE_ARCH} ${EXTRA_FLAGS} ")
    ELSE()
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsycl -fsycl-targets=spir64_gen ${EXTRA_FLAGS} ")
    ENDIF()
ENDIF()

IF(CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
    FIND_PACKAGE(IntelSYCL REQUIRED)
ENDIF()

IF (NEKTAR_ENABLE_DEVICE STREQUAL "SYCL-CUDA")
    FIND_PACKAGE(CUDAToolkit ${CUDA_MIN_VERSION} REQUIRED)
    SET(NEKTAR_SYCL_DEPENDS ${NEKTAR_SYCL_DEPENDS} CUDA::cudart CUDA::cuda_driver CUDA::nvrtc)
ELSEIF (NEKTAR_ENABLE_DEVICE STREQUAL "SYCL-HIP")
    IF(WIN32)
        SET(ROCM_ROOT
            "$ENV{HIP_PATH}"
            CACHE PATH
            "Root directory of the ROCm installation"
        )
    ELSE()
        SET(ROCM_ROOT
            "/opt/rocm"
            CACHE PATH
            "Root directory of the ROCm installation"
        )
    ENDIF()
    LIST(APPEND CMAKE_PREFIX_PATH "${ROCM_ROOT}")
    FIND_PACKAGE(HIP REQUIRED)
    FIND_LIBRARY(HIPRTC_LIB hiprtc HINTS ${HIP_PATH}/lib /opt/rocm/lib)
    SET(NEKTAR_SYCL_DEPENDS ${NEKTAR_SYCL_DEPENDS} hip::host ${HIPRTC_LIB})
ENDIF()
